export const MESSAGE_SENT		= 'MESSAGE_SENT';
export const LOAD_CHAT_ROOMS	= 'LOAD_CHAT_ROOMS';
export const CONNECT_TO_CHAT	= 'CONNECT_TO_CHAT';
export const UPDATE_MESSAGES	= 'UPDATE_MESSAGES';
export const UPDATE_CHAT_INPUT	= 'UPDATE_CHAT_INPUT';
