export const LOGIN			= 'LOGIN';
export const FAILED_LOGIN	= 'FAILED_LOGIN';
export const SUCCESS_LOGIN	= 'SUCCESS_LOGIN';

export const UPDATE_EMAIL		= 'UPDATE_EMAIL';
export const UPDATE_USERNAME	= 'UPDATE_USERNAME';
export const UPDATE_PASSWORD	= 'UPDATE_PASSWORD';
export const UPDATE_REPASSWORD	= 'UPDATE_REPASSWORD';