export const LOGIN			= 'LOGIN';
export const USER_LOGOUT	= 'USER_LOGOUT';
export const FAILED_LOGIN	= 'FAILED_LOGIN';
export const SUCCESS_LOGIN	= 'SUCCESS_LOGIN';

export const REGISTER_USER		= 'REGISTER_USER';
export const FAILED_REGISTER 	= 'FAILED_REGISTER';
export const SUCCESS_REGISTER 	= 'SUCCESS_REGISTER';

export const VERIFICATION_MAIL_SENT			= 'VERIFICATION_MAIL_SENT';
export const VERIFICATION_MAIL_FAILED		= 'VERIFICATION_MAIL_FAILED';
export const REQUIRE_EMAIL_VERIFICATION		= 'REQUIRE_EMAIL_VERIFICATION';
export const TRY_SENT_EMAIL_VERIFICATION	= 'TRY_SENT_EMAIL_VERIFICATION';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_EMAIL_CHANGE = 'FORGOT_EMAIL_CHANGE';
export const FAILED_RESET_PASSWORD = 'FAILED_RESET_PASSWORD';
export const SUCCESS_RESET_PASSWORD = 'SUCCESS_RESET_PASSWORD';
